src/objects/Sprint__c.object
<CustomObject>
    <description>A collection of User Stories to be worked on over a period of time.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Sprint</description>
        <inlineHelpText>Status of the Sprint</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sprint_Burndown__c.object
<CustomObject>
    <description>Captures total points and hours remaining in a Sprint at a date. Used for reports and Burndown charts.</description>
    <fields>
        <fullName>Date__c</fullName>
        <description>The date of this Sprint Burndown</description>
        <inlineHelpText>The date of this Sprint Burndown</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <description>The parent Sprint record for this Sprint Burndown</description>
        <inlineHelpText>The parent Sprint record for this Sprint Burndown</inlineHelpText>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>Sprint Burndowns</relationshipLabel>
        <relationshipName>Sprint_Burndowns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Total_Hours_Remaining__c</fullName>
        <description>Total hours remaining for all tasks in this Sprint as at the Sprint Burndown date</description>
        <inlineHelpText>Total hours remaining for all tasks in this Sprint as at the Sprint Burndown date</inlineHelpText>
        <label>Total Hours Remaining</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Points_Remaining__c</fullName>
        <description>Total points remaining for all tasks in this Sprint as at the Sprint Burndown date</description>
        <inlineHelpText>Total points remaining for all tasks in this Sprint as at the Sprint Burndown date</inlineHelpText>
        <label>Total Points Remaining</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sprint Burndown</label>
    <nameField>
        <displayFormat>SB-{0}</displayFormat>
        <label>Sprint Burndown Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sprint Burndowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User_Story__c.object
<CustomObject>
    <description>User Stories and Bugs</description>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Sprint this User Story is contained within</description>
        <inlineHelpText>The Sprint this User Story is contained within</inlineHelpText>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipName>UserStory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current status of this User Story</description>
        <inlineHelpText>The current status of this User Story</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <description>The Story Point value for this User Story. Scale: 0, 1, 2, 3, 5, 8, 13, 20, 40, 100</description>
        <inlineHelpText>The Story Point value for this User Story. Scale: 0, 1, 2, 3, 5, 8, 13, 20, 40, 100</inlineHelpText>
        <label>Story Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_Story_Task__c.object
<CustomObject>
    <description>Tasks for a User Story</description>
    <fields>
        <fullName>Remaining_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total number of hours remaining to complete this Task. The default value ensures the nightly SprintBurndown batch Apex doesn&apos;t fail.</description>
        <inlineHelpText>Total number of hours remaining to complete this Task</inlineHelpText>
        <label>Remaining Hours</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <description>The grandparent Sprint for this User Story. Set by a Workflow Field Update on every change.</description>
        <inlineHelpText>The grandparent Sprint for this User Story</inlineHelpText>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipName>User_Story_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this Task</description>
        <inlineHelpText>Status of this Task</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verify</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <description>The parent User Story</description>
        <inlineHelpText>The parent User Story</inlineHelpText>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Tasks</relationshipLabel>
        <relationshipName>User_Story_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story Task</label>
    <nameField>
        <label>Task Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SprintBurndownNightlyRollup.cls
global class SprintBurndownNightlyRollup implements Database.Batchable<sObject>, Database.Stateful {
	/*
		PURPOSE:
		- Rollup all 'Not Started' and 'In Progress' User Story (Points) and User Story Tasks (Hours)
		to a 'Sprint Burndown' record attached to the top level Sprint.
		- Ignore 'Done' User Story and User Story Task records in these Sprint Burndown records
		however do create a 'zero' Sprint Burndown record in the scenario where ALL User Stories are Done
		(by definition means all User Story Tasks are Done).

		- Can be run multiple times in the same day because only creates records once.
		- Allows for the query string to be set for testing.
		
		HISTORY:
		25-Nov-2011 Manu Erwin		Created
		26-Feb-2012 Manu Erwin		Fix: #41 - If ALL User Stories (and child Tasks) are DONE still create a zero Sprint Burndown
	*/

    // Map of Sprint Ids to Sprint Burndown records that will populated during the process
    global Map<Id, Sprint_Burndown__c> mapSprintIdToSprintBurndown;
    public String strQuery;

    // Constructor
    global SprintBurndownNightlyRollup () {
        System.debug(System.LoggingLevel.DEBUG, '##DEBUG: Constructor');
        mapSprintIdToSprintBurndown = new Map<Id, Sprint_Burndown__c>();
        if (strQuery == null){
	        System.debug(System.LoggingLevel.DEBUG, '##DEBUG: Using the default query for Production execution');
        	strQuery =	'SELECT Id, Sprint__c, Story_Points__c, Status__c, ' +
                            '(SELECT Id, User_Story__c, Remaining_Hours__c, Status__c FROM User_Story__c.User_Story_Tasks__r ' +
	                        'WHERE Status__c IN (\'Not Started\', \'In Progress\', \'Verify\')) ' +
                        'FROM User_Story__c ' +
                        'WHERE Sprint__r.Status__c = \'In Progress\'';
        } else {
	        System.debug(System.LoggingLevel.DEBUG, '##DEBUG: strQuery has been set - i.e., for testing');
        }
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        // Find all User Stories (and 'active' child User Story Tasks) where the 'parent' Sprint is active
        //      (assume status either formula based on end date OR updated by time based WF)
        System.debug(System.LoggingLevel.DEBUG, '##DEBUG: Start with strQuery: ' + strQuery);
        return Database.getQueryLocator(strQuery);
    }

    global void execute(Database.BatchableContext BC, List<User_Story__c> listUserStories) {
    	System.debug(System.LoggingLevel.DEBUG, '##DEBUG: execute');
        // loop through User Story records
        if (!listUserStories.isEmpty() ) {
            System.debug(System.LoggingLevel.DEBUG, '##DEBUG: number of User Story records to process:' + listUserStories.size());
	        for (User_Story__c userStory : listUserStories) {
	            System.debug(System.LoggingLevel.DEBUG, '##DEBUG: userStory:' + userStory);
	            Sprint_Burndown__c sprintBurndown;
	            // obtain SprintBurndown from map (using UserStory.SprintId) or
	            // create if first time (default rollup fields to zero and date to today)
	            if (mapSprintIdToSprintBurndown.containsKey(userStory.Sprint__c)) {
	                sprintBurndown = mapSprintIdToSprintBurndown.get(userStory.Sprint__c);
	                System.debug(System.LoggingLevel.DEBUG, '##DEBUG: sprintBurndown obtained from map: ' + sprintBurndown);
	            } else {
	                System.debug(System.LoggingLevel.DEBUG, '##DEBUG: Create new sprintBurndown');
	                // Note: Setting the Unique field so can upsert existing records
	                sprintBurndown = new Sprint_Burndown__c(Sprint__c = userStory.Sprint__c, Date__c = System.today(),
	                                Total_Points_Remaining__c = 0, Total_Hours_Remaining__c = 0,
	                                Unique_Sprint_Burndown__c = userStory.Sprint__c + '-' + String.valueOf(System.today()));
	            }

				if (userStory.Status__c == 'Not Started' || userStory.Status__c == 'In Progress') {
	                System.debug(System.LoggingLevel.DEBUG, '##DEBUG: User Story Status = Not Started/In Progress - add points: ' + userStory);
		            if (userStory.Story_Points__c != null) {
			            // add User Story Story Points to SprintBurndown
			            sprintBurndown.Total_Points_Remaining__c += userStory.Story_Points__c;
		            }
		
		            // loop child userStory Tasks
		            for (User_Story_Task__c userStoryTask : userStory.User_Story_Tasks__r) {
		                System.debug(System.LoggingLevel.DEBUG, '##DEBUG: User Story Task - add hours: ' + userStoryTask);
			            if (userStoryTask.Remaining_Hours__c != null) {
			                // add Hours Remaining to SprintBurndown
			                sprintBurndown.Total_Hours_Remaining__c += userStoryTask.Remaining_Hours__c;
			            }
		            }
				} else {
	                System.debug(System.LoggingLevel.DEBUG, '##DEBUG: User Story Status = Cancelled/Done - no calculations');
				}
	
	            // put SprintBurndown (back) into Map
	            System.debug(System.LoggingLevel.DEBUG, '##DEBUG: sprintBurndown before put into map: ' + sprintBurndown);
	            mapSprintIdToSprintBurndown.put(userStory.Sprint__c, sprintBurndown);
	        }
        } else {
	        System.debug(System.LoggingLevel.DEBUG, '##DEBUG: zero records to process:' + listUserStories.size());
        }
    }

    global void finish(Database.BatchableContext BC) {
	    System.debug(System.LoggingLevel.DEBUG, '##DEBUG: finish');
        if (!mapSprintIdToSprintBurndown.values().isEmpty()) {
            // attempt to upsert list of SprintBurndown records that have been populated during the batch process
            System.debug(System.LoggingLevel.INFO, '##DEBUG: about to upsert Sprint Burndowns: ' + mapSprintIdToSprintBurndown.values());
            // Upserting so that only one record per sprint is created per day 
            upsert mapSprintIdToSprintBurndown.values() Unique_Sprint_Burndown__c;
        } else {
            System.debug(System.LoggingLevel.INFO, '##DEBUG: no records to upsert');
        }
    }
}