src/objects/Sprint__c.object
<CustomObject>
    <description>A collection of User Stories to be worked on over a period of time.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End date for this Sprint</description>
        <inlineHelpText>End date for this Sprint</inlineHelpText>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start date for the Sprint</description>
        <inlineHelpText>Start date for the Sprint</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Sprint</description>
        <inlineHelpText>Status of the Sprint</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Sprint_Days__c</fullName>
        <description>Total number of days in the Sprint (including weekends).</description>
        <formula>End_Date__c -  Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total number of days in the Sprint (including weekends).</inlineHelpText>
        <label>Total Sprint Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_Story__c.object
<CustomObject>
    <description>User Stories and Bugs</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>The full detail for this User Story</description>
        <inlineHelpText>The full detail for this User Story</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <defaultValue>10000</defaultValue>
        <description>The absolute rank of this User Story in relation to other User Stories in the Product Backlog</description>
        <inlineHelpText>The absolute rank of this User Story in relation to other User Stories in the Product Backlog</inlineHelpText>
        <label>Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Sprint this User Story is contained within</description>
        <inlineHelpText>The Sprint this User Story is contained within</inlineHelpText>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipName>UserStory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current status of this User Story</description>
        <inlineHelpText>The current status of this User Story</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story_Indicator__c</fullName>
        <description>Visual indicator of User Story Status</description>
        <formula>IMAGE (
	CASE(Status__c , 
		&quot;Closed&quot;, &quot;/img/samples/flag_green.gif&quot;,
		&quot;In Progress&quot;, &quot;/img/samples/flag_yellow.gif&quot;,
		&quot;Not Started&quot;, &quot;/img/samples/flag_red.gif&quot;, 
		&quot;/s.gif&quot;), 
	&quot;User Story Status&quot;
)</formula>
        <inlineHelpText>Visual indicator of User Story Status</inlineHelpText>
        <label>Story Indicator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Story_Number__c</fullName>
        <description>Unique reference for each User Story</description>
        <displayFormat>US-{000}</displayFormat>
        <inlineHelpText>Unique reference for each User Story</inlineHelpText>
        <label>Story Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <description>The Story Point value for this User Story. Scale: 0, 1, 2, 3, 5, 8, 13, 20, 40, 100</description>
        <inlineHelpText>The Story Point value for this User Story. Scale: 0, 1, 2, 3, 5, 8, 13, 20, 40, 100</inlineHelpText>
        <label>Story Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_Story_Task__c.object
<CustomObject>
    <description>Tasks for a User Story</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Task description</description>
        <inlineHelpText>Task description</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Estimated_Hours__c</fullName>
        <description>Number of hours for this Task</description>
        <inlineHelpText>Number of hours for this Task</inlineHelpText>
        <label>Estimated Hours</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The rank of this User Story Task in relation to all others for the parent User Story</description>
        <inlineHelpText>The rank of this User Story Task in relation to all others for the parent User Story</inlineHelpText>
        <label>Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Remaining_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total number of hours remaining to complete this Task. The default value ensures the nightly SprintBurndown batch Apex doesn&apos;t fail.</description>
        <inlineHelpText>Total number of hours remaining to complete this Task</inlineHelpText>
        <label>Remaining Hours</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <description>The grandparent Sprint for this User Story. Set by a Workflow Field Update on every change.</description>
        <inlineHelpText>The grandparent Sprint for this User Story</inlineHelpText>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipName>User_Story_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this Task</description>
        <inlineHelpText>Status of this Task</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verify</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <description>The parent User Story</description>
        <inlineHelpText>The parent User Story</inlineHelpText>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Tasks</relationshipLabel>
        <relationshipName>User_Story_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story Task</label>
    <nameField>
        <label>Task Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VirtualWall_VfExt.cls
public with sharing class VirtualWall_VfExt {
	/*
		Purpose:
				- Provide list of existing User Stories and Tasks to be displayed to users on a VF page
				- Provide RemoteAction that updates Tasks after drag and drop to update Task Status.

		Used By:
				VirtualWall.page

		History:
		Created: 30-Dec-2012 By: Manu Erwin
	*/

    public VirtualWall_VfExt(ApexPages.StandardController stdController) {
    	this.sprint = (Sprint__c)stdController.getRecord();
    }

    private Sprint__c sprint;

    public List<StoryAndTasks> listStoryAndTasks {
        get {
            if (listStoryAndTasks == null) {
			    listStoryAndTasks = new List<StoryAndTasks>();
                for (User_Story__c oneUserStory : [SELECT Id, Name, Owner.Alias, Sprint__c, Story_Number__c, Status__c, Story_Indicator__c, 
	                						(SELECT Id, Name, Description__c,
	                						Status__c, Owner.Alias, Remaining_Hours__c
	                						FROM User_Story_Tasks__r ORDER BY Rank__c ASC)
                            			FROM User_Story__c
                            			WHERE Sprint__c = :sprint.Id
                            			ORDER BY Rank__c ASC] ) {
                	StoryAndTasks oneStoryAndTasks = new StoryAndTasks();
					oneStoryAndTasks.theStory = oneUserStory;
					for (User_Story_Task__c oneUserStoryTask : oneUserStory.User_Story_Tasks__r) {
						if (oneUserStoryTask.Status__c == 'Not Started') {
							oneStoryAndTasks.listTasksToDo.add(oneUserStoryTask);
						} else if (oneUserStoryTask.Status__c == 'In Progress') {
							oneStoryAndTasks.listTasksDoing.add(oneUserStoryTask);
						} else if (oneUserStoryTask.Status__c == 'Verify') {
							oneStoryAndTasks.listTasksVerify.add(oneUserStoryTask);
						} else if (oneUserStoryTask.Status__c == 'Done') {
							oneStoryAndTasks.listTasksDone.add(oneUserStoryTask);
						}
					}
					listStoryAndTasks.add(oneStoryAndTasks);
                }
            }
            System.debug(System.LoggingLevel.DEBUG, '## DEBUG: listStoryAndTasks before return: ' + listStoryAndTasks);
            return listStoryAndTasks;
        }
        set;
    }
    public Boolean userStoriesAndTasksExist {
    	get {
    		if (userStoriesAndTasksExist == null) {
				userStoriesAndTasksExist = false;
    			if (!listStoryAndTasks.isEmpty()) {
    				userStoriesAndTasksExist = true;
    			}
    		}
    		return userStoriesAndTasksExist;
    	}
    	set;
    }

	@RemoteAction
	public static Boolean updateTasks (String strKeyValuePairs) {
		Boolean bolSuccess = false;

		if (strKeyValuePairs != null && strKeyValuePairs != '') {
			System.debug(System.LoggingLevel.DEBUG, 'strKeyValuePairs has a value - process it: ' + strKeyValuePairs);
			// Split on & to get key/value pairs
			List<String> listKeyValuePairs = strKeyValuePairs.split('&');
			System.debug(System.LoggingLevel.DEBUG, 'listKeyValuePairs: ' + listKeyValuePairs);
			
			Set<Id> setTaskIds = new Set<Id>();
			Map<Id, String> mapTaskIdToStatus = new Map<Id, String>();
			Map<Id, Integer> mapTaskIdToRank = new Map<Id, Integer>();
	
			// ASSUMPTION: format is status~UserStoryId[]=taskId by this point
			//	e.g., done~a0d60000000vKjfAAE[]=a0o600000026wD8AAI
			Integer intCounter = 1;
			for (String strKeyValuePair : listKeyValuePairs) {
				System.debug(System.LoggingLevel.DEBUG, 'strKeyValuePair: ' + strKeyValuePair);
				Integer intLocationOfTilde = strKeyValuePair.indexOf('~');
				Integer intLocationOfEquals = strKeyValuePair.indexOf('=');
				String strStatus = strKeyValuePair.substring(0, intLocationOfTilde);
				String strTaskId = strKeyValuePair.substring(intLocationOfEquals + 1);
				setTaskIds.add(strTaskId);
				mapTaskIdToStatus.put(strTaskId, strStatus);
				mapTaskIdToRank.put(strTaskId, intCounter);
				intCounter++;
			}
			
			List<User_Story_Task__c> listTasksToUpdate = new List<User_Story_Task__c>();
			// Query for tasks and loop - ASSUMPTION: Less than 200 Tasks per User Story
			for (User_Story_Task__c oneTask : [SELECT Id, Status__c, Rank__c
										FROM User_Story_Task__c
										WHERE Id IN :setTaskIds]) {
				// for each task apply the status and rank from the map
				oneTask.Rank__c = mapTaskIdToRank.get(oneTask.Id);
				String strTaskStatus = mapTaskIdToStatus.get(oneTask.Id);
				if (strTaskStatus == 'toDo') {
					oneTask.Status__c = 'Not Started';
				} else if (strTaskStatus == 'doing') {
					oneTask.Status__c = 'In Progress';
				} else if (strTaskStatus == 'verify') {
					oneTask.Status__c = 'Verify';
				} else if (strTaskStatus == 'done') {
					oneTask.Status__c = 'Done';
				}
				listTasksToUpdate.add(oneTask);
			}
			
			// Update all Tasks
			System.debug(System.LoggingLevel.DEBUG, 'listTasksToUpdate before update: ' + listTasksToUpdate);
			// TODO: Handle errors with the DML and return false to force a revert
			update listTasksToUpdate;
			bolSuccess = true;
		} else {
			System.debug(System.LoggingLevel.DEBUG, 'strKeyValuePairs is null - nothing to process');
		}
		return bolSuccess;
	}

	/* TEST METHODS */
    @isTest static void noStoriesAndTasksExist_Test() {
		Sprint__c sprint = new Sprint__c (Name = 'noStoriesAndTasksExist_Test',
								Status__c = 'In Progress',
								Start_Date__c = System.today().addDays(-2),
								End_Date__c = System.today().addDays(+2));
		insert sprint;

		Test.startTest();
		Test.setCurrentPage(Page.VirtualWall);
		// Requery Sprint so that formula field retrieved
		sprint = [SELECT Id, Name, Status__c, Start_Date__c, End_Date__c, Total_Sprint_Days__c FROM Sprint__c WHERE Id = :sprint.Id];
		ApexPages.StandardController controller = new ApexPages.StandardController(sprint);
		VirtualWall_VfExt virtualWallCon = new VirtualWall_VfExt(controller);

		Boolean bolUserStoriesTasksExist = virtualWallCon.userStoriesAndTasksExist;
		Test.stopTest();

		System.assert(!bolUserStoriesTasksExist, 'There should be no User Story and Tasks: ' + bolUserStoriesTasksExist);
    }
    @isTest static void storiesAndTasksExist_Test() {
		Sprint__c sprint = new Sprint__c (Name = 'storiesAndTasksExist_Test-',
							Status__c = 'In Progress',
							Start_Date__c = System.today().addDays(-2),
							End_Date__c = System.today().addDays(+2));
		insert sprint;

		List<User_Story__c> listUserStories = new List<User_Story__c>();
		for (Integer intCounter = 0; intCounter < 4; intCounter++) {
			User_Story__c userStory = new User_Story__c(Name = 'storiesAndTasksExist_Test-' + sprint.Id + intCounter,
							Story_Points__c = 2, Sprint__c = sprint.Id);

			Integer intMod4 = System.Math.mod(intCounter, 4);
			if (intMod4 == 0) {
				userStory.Status__c = 'Not Started';
			} else if (intMod4 == 1) {
				userStory.Status__c = 'In Progress';
			} else if (intMod4 == 2) {
				userStory.Status__c = 'Done';
			} else if (intMod4 == 3) {
				userStory.Status__c = 'Cancelled';
			}
				
			listUserStories.add(userStory);
		}
		insert listUserStories;

		List<User_Story_Task__c> listUserStoryTasks = new List<User_Story_Task__c>();
		for (User_Story__c userStory : listUserStories) {
			if (userStory.Status__c == 'Not Started' || userStory.Status__c == 'In Progress') {
				System.debug('##DEBUG: userStory.Status not Done - create USTs: ' + userStory);
				for (Integer intCounter = 0; intCounter < 4; intCounter++) {
					User_Story_Task__c userStoryTask = new User_Story_Task__c(Name = 'storiesAndTasksExist_Test-' + userStory.Id + intCounter,
										User_Story__c = userStory.Id, Estimated_Hours__c = 2);
					Integer intMod4 = System.Math.mod(intCounter, 4);
					if (intMod4 == 0) {
						userStoryTask.Status__c = 'Not Started';
						userStoryTask.Remaining_Hours__c = 2;
					} else if (intMod4 == 1) {
						userStoryTask.Status__c = 'In Progress';
						userStoryTask.Remaining_Hours__c = 2;
					} else if (intMod4 == 2) {
						userStoryTask.Status__c = 'Verify';
						userStoryTask.Remaining_Hours__c = 0;
					} else if (intMod4 == 3) {
						userStoryTask.Status__c = 'Done';
						userStoryTask.Remaining_Hours__c = 0;
					}
					System.debug('##DEBUG: userStoryTask: ' + userStoryTask);
					listUserStoryTasks.add(userStoryTask);
				}
			} else {
				System.debug('##DEBUG: userStory.Status is Done - no processing: ' + userStory);
			}
		}
		insert listUserStoryTasks;

		Test.startTest();
		Test.setCurrentPage(Page.VirtualWall);
		// Requery Sprint so that formula field retrieved
		sprint = [SELECT Id, Name, Status__c, Start_Date__c, End_Date__c, Total_Sprint_Days__c FROM Sprint__c WHERE Id = :sprint.Id];
		ApexPages.StandardController controller = new ApexPages.StandardController(sprint);
		VirtualWall_VfExt virtualWallCon = new VirtualWall_VfExt(controller);

		Boolean bolUserStoriesTasksExist = virtualWallCon.userStoriesAndTasksExist;
		System.assert(bolUserStoriesTasksExist, 'There should be User Stories and Tasks: ' + bolUserStoriesTasksExist);

		List<StoryAndTasks> listStoryAndTasks = virtualWallCon.listStoryAndTasks;
		System.assert(!listStoryAndTasks.isEmpty(), 'There should be User Stories and Tasks: ' + listStoryAndTasks);

		Test.stopTest();
    }
}