src/objects/Sprint__c.object
<CustomObject>
    <description>A collection of User Stories to be worked on over a period of time.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End date for this Sprint</description>
        <inlineHelpText>End date for this Sprint</inlineHelpText>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start date for the Sprint</description>
        <inlineHelpText>Start date for the Sprint</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Sprint</description>
        <inlineHelpText>Status of the Sprint</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Sprint_Days__c</fullName>
        <description>Total number of days in the Sprint (including weekends).</description>
        <formula>End_Date__c -  Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total number of days in the Sprint (including weekends).</inlineHelpText>
        <label>Total Sprint Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sprint_Burndown__c.object
<CustomObject>
    <description>Captures total points and hours remaining in a Sprint at a date. Used for reports and Burndown charts.</description>
    <fields>
        <fullName>Date__c</fullName>
        <description>The date of this Sprint Burndown</description>
        <inlineHelpText>The date of this Sprint Burndown</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <description>The parent Sprint record for this Sprint Burndown</description>
        <inlineHelpText>The parent Sprint record for this Sprint Burndown</inlineHelpText>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>Sprint Burndowns</relationshipLabel>
        <relationshipName>Sprint_Burndowns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Total_Hours_Remaining__c</fullName>
        <description>Total hours remaining for all tasks in this Sprint as at the Sprint Burndown date</description>
        <inlineHelpText>Total hours remaining for all tasks in this Sprint as at the Sprint Burndown date</inlineHelpText>
        <label>Total Hours Remaining</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Points_Remaining__c</fullName>
        <description>Total points remaining for all tasks in this Sprint as at the Sprint Burndown date</description>
        <inlineHelpText>Total points remaining for all tasks in this Sprint as at the Sprint Burndown date</inlineHelpText>
        <label>Total Points Remaining</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sprint Burndown</label>
    <nameField>
        <displayFormat>SB-{0}</displayFormat>
        <label>Sprint Burndown Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sprint Burndowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SprintBurndown_VfExt_Test.cls
@isTest
private class SprintBurndown_VfExt_Test {

    static testMethod void noSprintBurndownsExist_Test() {
        Sprint__c sprint = new Sprint__c(Name = 'noSprintBurndownsExist', Status__c = 'In Progress',
        					Start_Date__c = System.today(), End_Date__c = System.today().addDays(30));
        insert sprint;

		Test.startTest();
		Test.setCurrentPage(Page.SprintBurndown);
		// Requery Sprint so that formula field retrieved
		sprint = [SELECT Id, Name, Status__c, Start_Date__c, End_Date__c, Total_Sprint_Days__c FROM Sprint__c WHERE Id = :sprint.Id];
		ApexPages.StandardController controller = new ApexPages.StandardController(sprint);
		SprintBurndown_VfExt sprintBurnCon = new SprintBurndown_VfExt(controller);

		Boolean bolBurndownsExist = sprintBurnCon.sprintBurndownsExist;
		System.assert(!bolBurndownsExist, 'There should be no Sprint Burndowns: ' + bolBurndownsExist);
    }
    static testMethod void sprintBurndownsExist_Test() {
        Sprint__c sprint = new Sprint__c(Name = 'sprintBurndownsExist_Test', Status__c = 'In Progress',
        					Start_Date__c = System.today(), End_Date__c = System.today().addDays(30));
        insert sprint;

		List<Sprint_Burndown__c> listSprintBurndowns = new List<Sprint_Burndown__c>();
		Integer intCountDays = 0;
		for (Integer intCount = 25; intCount > 0; intCount--) {
			Sprint_Burndown__c sprintBurn = new Sprint_Burndown__c(Sprint__c = sprint.Id, Date__c = System.today().addDays(intCountDays),
									Total_Points_Remaining__c = intCount, Total_Hours_Remaining__c = intCount);
			intCountDays++;
			listSprintBurndowns.add(sprintBurn);
		}
		insert listSprintBurndowns;

		Test.startTest();
		Test.setCurrentPage(Page.SprintBurndown);
		// Requery Sprint so that formula field retrieved
		sprint = [SELECT Id, Name, Status__c, Start_Date__c, End_Date__c, Total_Sprint_Days__c FROM Sprint__c WHERE Id = :sprint.Id];
		ApexPages.StandardController controller = new ApexPages.StandardController(sprint);
		SprintBurndown_VfExt sprintBurnCon = new SprintBurndown_VfExt(controller);

		Boolean bolBurndownsExist = sprintBurnCon.sprintBurndownsExist;
		System.assert(bolBurndownsExist, 'There should be Sprint Burndowns: ' + bolBurndownsExist);

		String strHoursRemaining = sprintBurnCon.getHoursRemainingOverTime();
		String strPointsRemaining = sprintBurnCon.getPointsRemainingOverTime();
    }
}