src/objects/User_Story__c.object
<CustomObject>
    <description>User Stories and Bugs</description>
    <label>User Story</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_Story_Task__c.object
<CustomObject>
    <description>Tasks for a User Story</description>
    <fields>
        <fullName>User_Story__c</fullName>
        <description>The parent User Story</description>
        <inlineHelpText>The parent User Story</inlineHelpText>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Tasks</relationshipLabel>
        <relationshipName>User_Story_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story Task</label>
    <nameField>
        <label>Task Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StoryAndTasks.cls
public class StoryAndTasks {
    public User_Story__c theStory {
        get {
            if (theStory == null) {
                theStory = new User_Story__c();
            }
            return theStory;
        }
        set;
    }
    public List<User_Story_Task__c> listTasksToDo {
        get {
            if (listTasksToDo == null) {
                listTasksToDo = new List<User_Story_Task__c>();
            }
            return listTasksToDo;
        }
        set;
    }
    public List<User_Story_Task__c> listTasksDoing {
        get {
            if (listTasksDoing == null) {
                listTasksDoing = new List<User_Story_Task__c>();
            }
            return listTasksDoing;
        }
        set;
    }
    public List<User_Story_Task__c> listTasksVerify {
        get {
            if (listTasksVerify == null) {
                listTasksVerify = new List<User_Story_Task__c>();
            }
            return listTasksVerify;
        }
        set;
    }
    public List<User_Story_Task__c> listTasksDone {
        get {
            if (listTasksDone == null) {
                listTasksDone = new List<User_Story_Task__c>();
            }
            return listTasksDone;
        }
        set;
    }
}