src/objects/Work__c.object
<CustomObject>
    <description>User Stories and Bugs</description>
    <label>Work</label>
    <nameField>
        <label>Work Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Work_Task__c.object
<CustomObject>
    <description>Sprint Backlog Tasks for a piece of Work</description>
    <fields>
        <fullName>Work__c</fullName>
        <description>The parent piece of Work</description>
        <inlineHelpText>The parent piece of Work</inlineHelpText>
        <label>Work</label>
        <referenceTo>Work__c</referenceTo>
        <relationshipLabel>Work Tasks</relationshipLabel>
        <relationshipName>Work_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Task</label>
    <nameField>
        <label>Work Task Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WorkAndTasks.cls
public class WorkAndTasks {
    public Work__c theWork {
        get {
            if (theWork == null) {
                theWork = new Work__c();
            }
            return theWork;
        }
        set;
    }
    public List<Work_Task__c> listTasksToDo {
        get {
            if (listTasksToDo == null) {
                listTasksToDo = new List<Work_Task__c>();
            }
            return listTasksToDo;
        }
        set;
    }
    public List<Work_Task__c> listTasksDoing {
        get {
            if (listTasksDoing == null) {
                listTasksDoing = new List<Work_Task__c>();
            }
            return listTasksDoing;
        }
        set;
    }
    public List<Work_Task__c> listTasksVerify {
        get {
            if (listTasksVerify == null) {
                listTasksVerify = new List<Work_Task__c>();
            }
            return listTasksVerify;
        }
        set;
    }
    public List<Work_Task__c> listTasksDone {
        get {
            if (listTasksDone == null) {
                listTasksDone = new List<Work_Task__c>();
            }
            return listTasksDone;
        }
        set;
    }
}