src/objects/Work__c.object
<CustomObject>
    <description>User Stories and Bugs</description>
    <label>Work</label>
    <nameField>
        <label>Work Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Work_Task__c.object
<CustomObject>
    <description>Sprint Backlog Tasks for a piece of Work</description>
    <fields>
        <fullName>Work__c</fullName>
        <description>The parent piece of Work</description>
        <inlineHelpText>The parent piece of Work</inlineHelpText>
        <label>Work</label>
        <referenceTo>Work__c</referenceTo>
        <relationshipLabel>Work Tasks</relationshipLabel>
        <relationshipName>Work_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Task</label>
    <nameField>
        <label>Work Task Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UpdateWorkTaskStatus_VfExt.cls
public with sharing class UpdateWorkTaskStatus_VfExt {

    public UpdateWorkTaskStatus_VfExt(ApexPages.StandardController controller) {
    }

    public List<Work_Task__c> listWorkTasks {
        get {
            if (listWorkTasks == null) {
                listWorkTasks = [SELECT Id, Name
                                FROM Work_Task__c
                                WHERE Work__c = 'a0d60000000u8KJ'];
            }
            return listWorkTasks;
        }
        set;
    }
}